Update github-actions-pipeline.yml

diff --git a/.github/workflows/github-actions-pipeline.yml b/.github/workflows/github-actions-pipeline.yml
--- a/.github/workflows/github-actions-pipeline.yml
+++ b/.github/workflows/github-actions-pipeline.yml
@@ -1,10 +1,48 @@
 name: CI Pipeline
 
 on: [push, pull_request]
+
 jobs:
   generate-token:
     runs-on: [self-hosted, linux, x64]
     steps:
-      - name: Read the variable
-        run: echo "My OS is ${{ vars.OSTYPE2 }}"
-       
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Generate access_token
+        id: generate_token
+        run: |
+          ACCESS_TOKEN=$(curl -X POST 'https://keycloakdev.codelessauto.io/realms/test/protocol/openid-connect/token' \
+          -H 'Content-Type: application/x-www-form-urlencoded' \
+          -d 'client_id=${{ vars.CLIENT_ID }}' \
+          -d 'grant_type=password' \
+          -d "username=${{ secrets.USERNAME }}" \
+          -d "password=${{ secrets.PASSWORD }}" | jq -r '.access_token')
+
+          if [ -z "$ACCESS_TOKEN" ]; then
+            echo "Error: Failed to generate access token"
+            exit 1
+          fi
+
+          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
+
+      - name: Display the extracted access_token
+        run: echo "Access Token:" "${{ steps.generate_token.outputs.ACCESS_TOKEN }}"
+
+      - name: Download Project
+        run: |
+          curl -f -X POST -H "Authorization: Bearer ${{ steps.generate_token.outputs.ACCESS_TOKEN }}" --output project.zip "${{ vars.PROJECT_URL }}"
+
+      - name: Extract Linux
+        if: runner.os != 'Windows'
+        run: |
+          mkdir project && cd project
+          unzip ../project.zip -d .
+          mkdir target
+
+      - name: Extract Windows
+        if: runner.os == 'Windows'
+        run: |
+          mkdir project && cd project
+          tar -xf ../project.zip
+          mkdir target
